name: "Hello World Workflow"

# Controls when the action will run. Triggers the workflow on push to the master or production branch.
on:
  push:
    branches:
      - master
      - production

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"

      - name : "Print current date" 
        run: date
