name: "Multi event pipeline / workflow" # name of the pipeline
on:
   push: #Event whenever push is made to the repository on the master branch
       branches:
           - master
           - test
   pull_request : #Event whenever a pull request is made to the repository
        branches:
            - master
   workflow_dispatch:

jobs:
    on-push: #job 1
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: #Steps to be executed in the job
            - name: "Running on Master/test Push" #step 1
              run : echo "Running on master/test Push"

    on-pull-request: #Job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: #steps to be executed in the job
            - name: "Running on the pull request" #Step 2
              run: echo "Running on the pull request"

    on-workflow-dispatch: #job 3
        if: github.event_name =='workflow_dispatch'
        runs-on: ubuntu-latest
        steps: #Steps to be executed in the job
            - name: "Running on the workflow dispatch"
              run: echo "Running on workflow dispatch"
